[package]
name = "tetris"
version = "0.1.0"
edition = "2021"
description = "tetris game for the web, using WebAssembly and TypeScript."

[dependencies]
wasm-bindgen = "0.2.78"
wee_alloc = "0.4.5"

[lib]
crate-type = ["cdylib"]